nginx:
  image: nginx:latest
  ports:
    - 8080:80
  volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  build: ./docker/php/
  ports:
    - "9000:9000"
  volumes:
    - ./application:/var/www/html
